name: sfsw_lab_1_spring
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.1.2
  flutter: 3.13.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0

flutter:
  uses-material-design: true
