name: sfsw_lab_1_spring
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.1.4
  flutter: 3.13.8

dependencies:
  boxy: ^2.1.2
  collection: ^1.18.0
  dynamic_color: ^1.6.8
  equatable: ^2.0.5
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_hooks: ^0.20.3
  flutter_mobx: ^2.1.0
  material_color_utilities: ^0.8.0
  meta: ^1.9.1
  mobx: ^2.2.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  flutter_test:
    sdk: flutter
  leancode_lint:
    git:
      url: https://github.com/leancodepl/flutter_corelibrary
      path: packages/leancode_lint
      ref: afadadeabc4912d06d1926183f6d0aa9fd89f2a4
  mobx_codegen: ^2.4.0

dependency_overrides:
  collection: ^1.18.0
  material_color_utilities: ^0.8.0

flutter:
  uses-material-design: true
