name: sfsw_lab_1_spring
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.1.2
  flutter: 3.13.4

dependencies:
  dynamic_color: ^1.6.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.2
  flutter_mobx: ^2.1.0
  material_color_utilities: ^0.8.0
  mobx: ^2.2.0
  window_manager: ^0.3.6

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0
  mobx_codegen: ^2.4.0

dependency_overrides:
  material_color_utilities: ^0.8.0

flutter:
  uses-material-design: true
